
env = SConscript('godot-cpp/SConstruct')


env.Append(CPPPATH="src/")


src = Glob("src/*.cpp")
src.append(Glob("src/height_brushes/*.cpp"))

libpath = '../libs/MTerrain{}{}'.format( env['suffix'], env['SHLIBSUFFIX'] )
sharedlib = env.SharedLibrary(libpath, src)
Default(sharedlib)
