name: Builds

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
    build_android:
        uses: ./.github/workflows/build_android.yml
    # build_ios:
    #     uses: ./.github/workflows/build_ios.yml
    build_linux:
        uses: ./.github/workflows/build_linux.yml
    build_windows:
        uses: ./.github/workflows/build_windows.yml
    build_web:
        uses: ./.github/workflows/build_web.yml
    group_builds:
        needs: [build_android, build_linux, build_windows, build_web]
        uses: ./.github/workflows/group_builds.yml